"use client";
import { useState } from "react";
import { catalog, stores } from "../../data/marketplace";
import { useCommerce } from "../CommerceContext";
import { useDemoOperations } from "../DemoOperations";
import styles from "./partner.module.css";

export default function PartnerOperations({ section }: { section: string }) {
  const { state, ready } = useCommerce();
  const operations = useDemoOperations();
  const [storeId, setStoreId] = useState("heritage");
  const [selected, setSelected] = useState(catalog[0].id);
  const [size, setSize] = useState("M");
  const [location, setLocation] = useState("Main showroom");
  const [prices, setPrices] = useState<Record<number, string>>({});
  const [collection, setCollection] = useState<number[]>([]);
  const [discount, setDiscount] = useState(10);
  const [campaign, setCampaign] = useState(false);
  const [pairing, setPairing] = useState(false);
  const [available, setAvailable] = useState([true, true, false]);
  const [title, setTitle] = useState("A closer look at Indian craftsmanship");
  const [notice, setNotice] = useState("");
  const product = catalog.find(item => item.id === selected) ?? catalog[0];
  const storeProducts = catalog.filter(item => item.storeId === storeId);
  const activeOrders = state.orders.map(order => ({ ...order, lines: order.lines.filter(line => catalog.find(item => item.id === line.productId)?.storeId === storeId) })).filter(order => order.lines.length);
  const broadcast = operations.broadcasts[storeId];
  function selectStore(id: string) { setStoreId(id); const first = catalog.find(item => item.storeId === id); if (first) { setSelected(first.id); setSize(first.sizes[0]); } }
  const chooseProduct = <div className={styles.filters}><label>Catalog product<select value={selected} onChange={event => { const next = catalog.find(item => item.id === Number(event.target.value))!; setSelected(next.id); setSize(next.sizes[0]); }}>{storeProducts.map(item => <option key={item.id} value={item.id}>{item.name}</option>)}</select></label><label>Variant<select value={size} onChange={event => setSize(event.target.value)}>{product.sizes.map(value => <option key={value}>{value}</option>)}</select></label></div>;
  return <section className={styles.operations} aria-label="Connected demo operations">
    <div className={styles.filters}><label>Connected demo retailer<select value={storeId} onChange={event => selectStore(event.target.value)}>{stores.map(store => <option key={store.id} value={store.id}>{store.name}</option>)}</select></label></div>
    <p className={styles.muted}>Connected workspace uses your current browser-tab shopping brief, orders, requests and holds. The heritage snapshot below is separate fictional seed data. Draft pricing and merchandising stay on this page.</p>
    {notice && <p className={styles.notice} role="status">{notice}</p>}
    {section === "Overview" && <div className={styles.metrics}>{[["Your local orders", activeOrders.length], ["Open requests", operations.requests.filter(request => request.status === "waiting" && storeProducts.some(p => p.id === request.productId)).length], ["Local held units", operations.holds.filter(hold => storeProducts.some(p => p.id === hold.productId)).length], ["Cart units · all stores", state.cart.reduce((sum, line) => sum + line.quantity, 0)]].map(([label, value]) => <article className={styles.card} key={label}><p>{label}</p><strong className={styles.metric}>{value}</strong><small>Current demo activity</small></article>)}</div>}
    {(section === "Products" || section === "Inventory") && <article className={styles.card}><h2>Connected catalog & variant holds</h2>{chooseProduct}<p>{product.sku} · {product.retailer} · ${product.price} USD storefront price</p><div className={styles.filters}><label>Mock stock location<select value={location} onChange={event => setLocation(event.target.value)}><option>Main showroom</option><option>City stockroom</option></select></label><label>Draft price (USD)<input type="number" min="1" step="0.01" value={prices[selected] ?? product.price} onChange={event => setPrices({ ...prices, [selected]: event.target.value })} /></label></div><p>Illustrative {location} stock: {location === "Main showroom" ? 8 : 5} units. Shared holds are pooled by product/size across locations; location allocation is a demo snapshot only.</p><button className={styles.primary} onClick={() => { const value = Number(prices[selected] ?? product.price); setNotice(Number.isFinite(value) && value > 0 ? `Draft price $${value.toFixed(2)} saved for review. Storefront and checkout pricing remain at $${product.price}.` : "Enter a valid positive draft price."); }}>Save draft price</button>{" "}<button className={styles.primary} disabled={!operations.ready} onClick={() => operations.reserve(selected, size)}>Hold variant for 30 minutes</button><p>No physical stock is reserved. Expiring holds are shared with shopping surfaces.</p>{operations.holds.filter(hold => storeProducts.some(item => item.id === hold.productId)).map(hold => <div className={styles.hold} key={hold.id}><span>{catalog.find(item => item.id === hold.productId)?.name} · {hold.size} · expires {new Date(hold.expiresAt).toLocaleTimeString()}</span><button className={styles.textButton} onClick={() => operations.release(hold.id)}>Release hold</button></div>)}</article>}
    {section === "Collections" && <article className={styles.card}><h2>The celebration edit</h2><p>Select products for a local draft collection. USD pricing excludes delivery and duties.</p>{catalog.map(item => <label key={item.id} className={styles.check}><input type="checkbox" checked={collection.includes(item.id)} onChange={() => setCollection(collection.includes(item.id) ? collection.filter(id => id !== item.id) : [...collection, item.id])} />{item.name} · ${item.price} · {item.retailer}</label>)}<p>{collection.length} products · combined list price ${catalog.filter(item => collection.includes(item.id)).reduce((sum, item) => sum + item.price, 0)}</p><button className={styles.primary} disabled={!collection.length} onClick={() => setNotice("Collection saved as a local draft for review. No storefront publication occurred.")}>Save collection draft</button></article>}
    {section === "Promotions" && <article className={styles.card}><h2>Promotion simulator</h2>{chooseProduct}<div className={styles.filters}><label>Discount %<input type="number" min="0" max="50" value={discount} onChange={event => setDiscount(Math.max(0, Math.min(50, Number(event.target.value) || 0)))} /></label></div><p>${product.price} → ${(product.price * (1 - discount / 100)).toFixed(2)} merchandise price · Preview only.</p><button className={styles.primary} onClick={() => setCampaign(!campaign)}>{campaign ? "Pause" : "Activate"} local draft campaign</button><p role="status">{campaign ? "Active in simulator" : "Paused"}. Coupon previews never alter checkout pricing. No stacking, shipping or duty discount.</p><h3>Bundle preview</h3><p>Two eligible products, $15 off combined list price; eligibility review required. Configure a draft collection before review.</p></article>}
    {section === "Cross-sell" && <article className={styles.card}><h2>Context-aware merchandising</h2><p>Current shopper: {state.brief.intent || "No intent submitted"} · budget {state.brief.budget ? `$${state.brief.budget}` : "unknown"} · size {state.brief.size || "unknown"}.</p><p>Upsell preview: compare the ${catalog[0].price} {catalog[0].name} with other catalog outfits. Honor the stated budget before offering a higher price.</p><button className={styles.primary} onClick={() => setPairing(!pairing)}>{pairing ? "Remove" : "Save"} occasion pairing draft</button><p role="status">{pairing ? "Pairing saved for associate review; never automatically added to customer cart." : "No connected pairing draft saved."}</p></article>}
    {section === "Live Requests" && <article className={styles.card}><h2>Requests from this demo visit</h2><p>Brief: {state.brief.intent || "No shopping intent yet"} · {state.brief.destination || "Destination not provided"}</p>{operations.requests.filter(request => storeProducts.some(item => item.id === request.productId)).map(request => <div className={styles.hold} key={request.id}><div><strong>{request.id} · {catalog.find(item => item.id === request.productId)?.name}</strong><p>{request.brief.intent || "Product walkthrough"} · {request.brief.budget ? `$${request.brief.budget}` : "Budget unknown"} · {request.status}</p></div><button className={styles.primary} disabled={request.status === "assigned" || !available.some(Boolean)} onClick={() => operations.assignRequest(request.id)}>Assign available associate</button></div>)}<p>Only locally requested sessions appear here. Assignment does not contact anyone or start a camera.</p></article>}
    {section === "Orders" && <article className={styles.card}><h2>Connected customer orders</h2>{!ready ? <p>Loading local orders…</p> : !activeOrders.length ? <p>No orders for this retailer yet. Create a mock order from Explore Stores.</p> : activeOrders.map(order => <div key={order.id} className={styles.hold}><div><strong>{order.id}</strong><p>{order.lines.map(line => `${catalog.find(item => item.id === line.productId)?.name} · ${line.size} × ${line.quantity}`).join(" / ")}</p><p>Retailer subtotal ${order.lines.reduce((sum,line) => sum + (catalog.find(item => item.id === line.productId)?.price ?? 0) * line.quantity, 0)} · full order ${order.total} · {order.brief.destination}</p><p className={styles.warning}>Event: {order.brief.eventDate || "Not provided"}. Open Flow for the shared order’s current simulated stage, ETA and risk; those scenarios can change independently of this order snapshot.</p></div></div>)}<a href="/flow" className={styles.textButton}>Open IndiaAnytime Flow →</a></article>}
    {section === "Associates" && <div className={styles.requests}>{["Neha", "Arjun", "Meera"].map((name, i) => <article className={styles.card} key={name}><h2>{name}</h2><p>Fictional associate · {i === 0 ? "Silks & occasion wear" : i === 1 ? "Catalog & fit guidance" : "Craft & accessories"}</p><p>{available[i] ? "Available for mock assignments" : "Offline"}</p><button className={styles.primary} onClick={() => setAvailable(available.map((value, index) => index === i ? !value : value))}>Set {available[i] ? "offline" : "available"}</button><p>Personal camera off · recording off. Availability lasts for this page visit.</p></article>)}</div>}
    {section === "Analytics" && <article className={styles.card}><h2>Measured local activity</h2><div className={styles.metrics}>{[["Retailer orders", activeOrders.length], ["Retailer merchandise USD", activeOrders.reduce((sum, order) => sum + order.lines.reduce((value, line) => value + (catalog.find(item => item.id === line.productId)?.price ?? 0) * line.quantity, 0), 0)], ["All assigned requests", operations.requests.filter(request => request.status === "assigned").length], ["All active holds", operations.holds.length]].map(([label, value]) => <div key={label}><p>{label}</p><strong className={styles.metric}>{value}</strong></div>)}</div><p>Counts derive from this tab only. Traffic, conversion, revenue collection and audience size are not measured. No analytics service is connected.</p></article>}
    {section === "Live Studio" && <article className={styles.card}><span className={broadcast?.live ? styles.warning : styles.pill}>{broadcast?.live ? "MOCK BROADCAST LIVE" : "OFF AIR"}</span><h2>Retailer Live Studio</h2><p>Product-only public broadcast simulation. Shopper camera/mic and associate personal camera are always off. Recording is off; no media devices or real streams are used.</p>{chooseProduct}<div className={styles.filters}><label>Broadcast title<input maxLength={100} value={title} onChange={event => setTitle(event.target.value)} /></label></div><div className={styles.stage}><strong>{broadcast?.live ? broadcast.title : title}</strong><p>Product display · {catalog.find(item => item.id === (broadcast?.live ? broadcast.productId : selected))?.name}</p><span>PERSONAL VIDEO OFF · MICROPHONES OFF · NO RECORDING</span></div><button className={styles.primary} disabled={!operations.ready || !title.trim()} onClick={() => operations.setBroadcast(storeId, { live: !broadcast?.live, title: title.trim(), productId: selected })}>{broadcast?.live ? "End mock broadcast instantly" : "Start product-only mock broadcast"}</button>{" "}{broadcast?.live && <button className={styles.textButton} onClick={() => operations.setBroadcast(storeId, { live: true, title: title.trim() || "Product walkthrough", productId: selected })}>Update featured product</button>}<p>Broadcast status and featured product are shared with the public Store Live surface in this tab.</p></article>}
  </section>;
}
