"use client";
import Link from "next/link";
import { useEffect, useState } from "react";
import { useCommerce, ShoppingBrief } from "../CommerceContext";
import { catalog, stores } from "../../data/marketplace";
import { assessDelivery, flowStages, initialJourney, Journey } from "../../data/flow";
import styles from "./flow.module.css";

export default function Flow() {
  const { state, ready } = useCommerce();
  const [selected, setSelected] = useState("");
  const [journeys, setJourneys] = useState<Record<string, Journey>>({});
  const [loaded, setLoaded] = useState(false);
  useEffect(() => { let active = true; queueMicrotask(() => { if (!active) return; try { const raw = JSON.parse(sessionStorage.getItem("indiaanytime.flow.v1") ?? "{}"); if (raw && typeof raw === "object") setJourneys(Object.fromEntries(Object.entries(raw).filter((entry): entry is [string, Journey] => { const value = entry[1]; const j = value as Journey; return j && Number.isInteger(j.stage) && j.stage >= 0 && j.stage <= 7 && Number.isInteger(j.delayDays) && j.delayDays >= 0 && j.delayDays <= 14 && typeof j.expedited === "boolean" && Array.isArray(j.events) && j.events.every(e => typeof e === "string"); }))); } catch { /* Start a fresh local simulation. */ } setLoaded(true); }); return () => { active = false; }; }, []);
  useEffect(() => { if (loaded) { try { sessionStorage.setItem("indiaanytime.flow.v1", JSON.stringify(journeys)); } catch { /* Changes still work for this visit. */ } } }, [journeys, loaded]);
  const order = state.orders.find(o => o.id === selected) ?? state.orders[0];
  const journey = order ? journeys[order.id] ?? initialJourney : initialJourney;
  const timing = assessDelivery(order?.brief.eventDate ?? state.brief.eventDate, order?.brief.destination ?? state.brief.destination, journey);
  const orderStores = stores.filter(s => order?.lines.some(line => catalog.find(p => p.id === line.productId)?.storeId === s.id));
  function change(patch: Partial<Journey>, event: string) { if (!order || !loaded) return; setJourneys(current => { const previous = current[order.id] ?? initialJourney; return { ...current, [order.id]: { ...previous, ...patch, events: [event, ...previous.events].slice(0,20) } }; }); }
  return <main className={styles.page}>
    <nav className={styles.nav}><Link href="/" className={styles.brand}>IndiaAnytime <small>FLOW</small></Link><div><Link href="/explore">Explore Stores</Link><Link href="/explore#shopping-bag">Shopping bag</Link><Link href="/partner">Partner</Link></div></nav>
    <div className={styles.demo}>FICTIONAL LOGISTICS SIMULATION · No carrier, customs, payment or customer notification service is connected.</div>
    <div className={styles.content}><header className={styles.hero}><p>FROM A STOREFRONT TO YOUR DOOR</p><h1>Every stop.<br />One clear journey.</h1><span>IndiaAnytime Flow keeps your occasion in view, across stores and across borders.</span></header>
    <ShoppingBrief />
    <section className={styles.metrics}>{[["Connected demo orders", state.orders.length], ["Stores in this shipment", orderStores.length], ["Delivery confidence", timing.risk], ["Event deadline", order?.brief.eventDate || "Not provided"]].map(([label,value]) => <article key={label}><small>{label}</small><strong>{value}</strong></article>)}</section>
    {!ready || !loaded ? <p role="status">Loading this tab’s shopping trip…</p> : !order ? <section className={styles.empty}><h2>Your first journey starts with a discovery.</h2><p>Add products from one or more stores, set a US destination in your brief, then create a mock order. It appears here and in Partner automatically.</p><Link href="/explore">Explore the marketplace →</Link><p>No sample shipment is presented as your order.</p></section> : <>
    <section className={styles.orderSelect}><label>Track an order<select value={order.id} onChange={e => setSelected(e.target.value)}>{state.orders.map(o => <option key={o.id} value={o.id}>{o.id} · ${o.total} · {o.brief.destination}</option>)}</select></label><p>Order brief is a snapshot at checkout. Editing your current brief does not rewrite this order.</p></section>
    <div className={styles.columns}><section className={styles.card}><p className={styles.eyebrow}>SHIPMENT CONTROL TOWER</p><h2>{flowStages[journey.stage]}</h2><p>Destination: {order.brief.destination} · {order.brief.occasion || "Occasion unconfirmed"}</p><ol className={styles.timeline}>{flowStages.map((stage,index) => <li key={stage} className={index < journey.stage ? styles.done : index === journey.stage ? styles.current : ""} aria-current={index === journey.stage ? "step" : undefined}><span>{index < journey.stage ? "✓" : index + 1}</span><div><strong>{stage}</strong><small>{index < journey.stage ? "Completed in simulation" : index === journey.stage ? "Current simulated stage" : "Pending"}</small></div></li>)}</ol><div className={styles.actions}><button disabled={journey.stage >= 7} onClick={() => change({ stage: journey.stage + 1 }, `Demo update: ${flowStages[journey.stage + 1]}. No external notification sent.`)}>Simulate next stage →</button><button disabled={journey.stage >= 7 || journey.delayDays >= 14} onClick={() => change({ delayDays: Math.min(14, journey.delayDays + 2) }, "Simulated exception: 2-day processing delay added to ETA.")}>Simulate 2-day delay</button><button onClick={() => change({ ...initialJourney }, "Journey reset to retailer pickup in this demo.")}>Reset journey</button></div></section>
    <aside className={styles.card}><p className={styles.eyebrow}>THE OCCASION COMES FIRST</p><h2>{timing.risk}</h2><p className={styles.eta}>{journey.stage === 7 ? "Delivered · simulation only" : `${timing.earliest} — ${timing.latest}`}</p><p>Illustrative arrival window · {timing.low}–{timing.high} days from today. This moving scenario is recalculated when viewed, not a carrier estimate.</p><p>Event: <strong>{order.brief.eventDate || "Not provided"}</strong></p><p>{timing.recommendation}</p><div className={styles.risk}><strong>Unverified dependencies</strong><p>Store pickup, consolidation, export paperwork, customs inspection, international transport and US delivery.</p></div><label className={styles.expedite}><input type="checkbox" checked={journey.expedited} disabled={journey.stage >= 7} onChange={e => change({ expedited: e.target.checked }, e.target.checked ? "Expedite scenario selected: illustrative $35 extra, up to 2 days faster. No service booked." : "Standard delivery scenario restored.")} /><span>Compare expedite scenario<br /><small>Illustrative +$35, up to 2 days faster. No quote or charge.</small></span></label><p>Merchandise: ${order.total} USD. Shipping, duties and taxes are unknown. Expedite cost is a fictional comparison, excluded from order total.</p></aside></div>
    <section className={styles.card}><p className={styles.eyebrow}>MULTI-STORE CONSOLIDATION</p><h2>{orderStores.length > 1 ? `${orderStores.length} stores. One consolidated demo shipment.` : "One store. One demo shipment."}</h2><div className={styles.stores}>{orderStores.map(store => <article key={store.id}><h3>{store.name}</h3><p>{store.district}, {store.city} → Hyderabad consolidation hub</p>{order.lines.filter(line => catalog.find(p => p.id === line.productId)?.storeId === store.id).map(line => <p key={`${line.productId}-${line.size}`}>{catalog.find(p => p.id === line.productId)?.name} · {line.size} × {line.quantity}</p>)}<small>{journey.stage >= 2 ? "Consolidated in simulation" : "Pickup / consolidation pending"}</small></article>)}</div><p>Route: Hyderabad hub → export/customs → international transit → US import/customs → destination last mile. No actual routing or customs advice is provided.</p></section>
    <section className={styles.card} aria-live="polite"><p className={styles.eyebrow}>LOCAL EVENT FEED</p><h2>Updates without the guesswork.</h2>{journey.events.length ? <ul>{journey.events.map((event,index) => <li key={`${index}-${event}`}>{event}</li>)}</ul> : <p>Mock order received. Simulate a stage or delay to see updates here.</p>}<p>Only this tab displays these updates. No email, SMS or push notification is sent.</p></section>
    </>}
    <footer>India. Always Open. · Shop India like you’re there.</footer></div>
  </main>;
}
