"use client";
import Link from "next/link";
import { useState } from "react";
import { catalog, deliveryRisk, stores, subtotal, tripSuggestions } from "../../data/marketplace";
import { ShoppingBrief, useCommerce } from "../CommerceContext";
import ProductQuestions from "../ProductQuestions";
import ShoppingSessions from "../ShoppingSessions";
import styles from "./street.module.css";

type Product = typeof catalog[number];
export default function Explore() {
  const { state, ready, message, add, remove, checkout } = useCommerce();
  const [city, setCity] = useState("Hyderabad");
  const [district, setDistrict] = useState("All districts");
  const [storeId, setStoreId] = useState<string | null>(null);
  const [question, setQuestion] = useState<Product | null>(null);
  const [schedule, setSchedule] = useState<string | null>(null);
  const [sizes, setSizes] = useState<Record<number,string>>({});
  const [compare, setCompare] = useState<number[]>([]);
  const [street, setStreet] = useState(false);
  const store = stores.find(item => item.id === storeId);
  const visibleStores = stores.filter(item => item.city === city && (district === "All districts" || item.district === district));
  const total = subtotal(state.cart);
  const suggested = tripSuggestions(state.brief);
  const context = Object.entries(state.brief).filter(([,value]) => value).map(([key,value]) => `${key}: ${value}`).join(" · ");
  const selected = catalog.filter(item => compare.includes(item.id));
  const timing = deliveryRisk(state.brief, Math.max(0, ...state.cart.map(line => catalog.find(p => p.id === line.productId)?.etaDays ?? 0)));
  function sizeFor(product: Product) { return sizes[product.id] ?? (product.sizes.includes(state.brief.size) ? state.brief.size : product.sizes.length === 1 ? product.sizes[0] : ""); }
  return <main className={styles.page}>
    <nav className={styles.nav}><Link className={styles.logo} href="/">IndiaAnytime<small>India. Always Open.</small></Link><div><Link href="/">Ask IndiaAnytime</Link><a href="#shopping-bag">Bag ({state.cart.reduce((sum,line) => sum + line.quantity, 0)})</a><Link href="/partner">Partner ↗</Link></div></nav>
    <div className={styles.demo}>FICTIONAL PROTOTYPE · Stores, ratings, stock, availability and logistics are illustrative. No purchases, bookings or live connections.</div>
    <section className={styles.hero}><p>A LITTLE WANDER. A BEAUTIFUL FIND.</p><h1>Shop India like<br />you’re there.</h1><div>From celebrated storefronts to the little shop around the corner.<br />Your next discovery is just a few steps away.</div></section>
    <div className={styles.content}><ShoppingBrief />{message && <p role="status" className={styles.feedback}>{message}</p>}
      <section className={styles.discovery} aria-labelledby="explore-heading"><div className={styles.sectionHead}><div><p className={styles.eyebrow}>EXPLORE STORES</p><h2 id="explore-heading">Where shall we wander?</h2></div><button aria-pressed={street} onClick={() => setStreet(!street)}>{street ? "Show tile view" : "Walk the street →"}</button></div>
        <div className={styles.cities}>{["Hyderabad", "Bengaluru", "Chennai", "Mumbai", "Delhi"].map(name => <button key={name} aria-pressed={city === name} onClick={() => { setCity(name); setDistrict("All districts"); setStoreId(null); }}>{name}{name !== "Hyderabad" && <small>Concept</small>}</button>)}</div>
        {city === "Hyderabad" && <div className={styles.filters}><label>Shopping district<select value={district} onChange={event => { setDistrict(event.target.value); setStoreId(null); }}>{["All districts", "Banjara Hills", "Old City"].map(name => <option key={name}>{name}</option>)}</select></label><p>4 fictional storefronts · A prototype of browsing a shopping district</p></div>}
        {visibleStores.length === 0 ? <div className={styles.empty}><h3>{city} is on our wish list.</h3><p>This city is a concept preview. The working mock catalog is in Hyderabad.</p><button onClick={() => setCity("Hyderabad")}>Explore Hyderabad →</button></div> : <div className={street ? styles.street : styles.tiles}>{visibleStores.map(item => <article key={item.id} className={styles.store}><div className={styles.facade} style={{ backgroundColor: item.color }}><div className={styles.awning} /><span>{item.initials}</span><h3>{item.name}</h3><p>{item.specialty}</p><div className={styles.window}>INDIA. ALWAYS OPEN.</div></div><div className={styles.storeInfo}><p>{item.type} · {item.district}</p><small>{item.status} · Mock</small><button onClick={() => { setStoreId(item.id); document.getElementById("store-collection")?.scrollIntoView({ behavior: "smooth", block: "start" }); }} aria-pressed={storeId === item.id}>Enter store ↗</button></div></article>)}</div>}
      </section>
      <section id="store-collection" className={styles.collection}><div className={styles.sectionHead}><div><p className={styles.eyebrow}>{store ? `${store.type} · ${store.district}` : "THE OCCASION EDIT"}</p><h2>{store?.name ?? "Discover across stores"}</h2></div>{store && <button onClick={() => setStoreId(null)}>All collections</button>}</div><p className={styles.context}>Your brief travels with you: {context || "Add your preferences above. Size, destination and event date are not yet confirmed."}</p>
        <div className={styles.products}>{catalog.filter(product => !store || product.storeId === store.id).map(product => <article key={product.id} className={styles.product}>
          {product.image ? <div className={styles.productImage} style={{ backgroundImage: `url(${product.image})` }} role="img" aria-label={product.name} /> : <div className={styles.textile} role="img" aria-label="Illustrative woven gold textile pattern">Deccan<br /><em>Threadworks</em></div>}
          <div className={styles.productBody}><small>{product.retailer} · Fictional</small><h3>{product.name}</h3><p>{product.description}</p><strong>${product.price} <small>USD</small></strong><p className={styles.fine}>Mock rating {product.rating}/5 · {product.reviews} fictional reviews</p><label>Demo size<select value={sizeFor(product)} onChange={event => setSizes({ ...sizes, [product.id]: event.target.value })}><option value="">Select size</option>{product.sizes.map(size => <option key={size}>{size}</option>)}</select></label><button className={styles.primary} disabled={!ready || !sizeFor(product)} onClick={() => add(product.id, sizeFor(product))}>Add to mock bag</button><div className={styles.actions}><button onClick={() => setQuestion(product)}>Ask about item</button><button onClick={() => setSchedule(product.name)}>Plan Shop Live</button><button aria-pressed={compare.includes(product.id)} disabled={compare.length >= 3 && !compare.includes(product.id)} onClick={() => setCompare(compare.includes(product.id) ? compare.filter(id => id !== product.id) : [...compare, product.id])}>{compare.includes(product.id) ? "Remove comparison" : "Compare"}</button></div></div>
        </article>)}</div>
      </section>
      {selected.length > 0 && <section className={styles.panel}><div className={styles.sectionHead}><h2>Compare your discoveries</h2><button onClick={() => setCompare([])}>Clear comparison</button></div><p>Up to 3 products. All details are fictional; listed sizes are not verified inventory.</p><div className={styles.table}><table><caption>Cross-store comparison</caption><thead><tr><th>Product</th>{selected.map(p => <th key={p.id}>{p.name}</th>)}</tr></thead><tbody>{["Store", "Price", "Sizes", "Delivery"].map(label => <tr key={label}><th>{label}</th>{selected.map(p => <td key={p.id}>{label === "Store" ? p.retailer : label === "Price" ? `$${p.price} USD` : label === "Sizes" ? p.sizes.join(", ") : p.delivery}</td>)}</tr>)}</tbody></table></div></section>}
      <section className={styles.trip}><div><p className={styles.eyebrow}>INDIAANYTIME AGENT · RULE-BASED DEMO</p><h2>Make a little trip of it.</h2><p>A lower-priced outfit, then a complementary artisan accent when your merchandise budget allows. This suggestion checks listed sizes and prices; it does not interpret every detail of your intent or occasion.</p><p>Shipping, duties and taxes are unknown and excluded. Allow extra budget before making any real decision.</p></div><div>{suggested.length ? <><ol>{suggested.map(p => <li key={p.id}><strong>{p.retailer}</strong><span>{p.name} · ${p.price}</span><button onClick={() => { setCity("Hyderabad"); setDistrict("All districts"); setStoreId(p.storeId); document.getElementById("store-collection")?.scrollIntoView({ behavior: "smooth" }); }}>Visit this stop →</button></li>)}</ol><p>Suggested merchandise total: <strong>${suggested.reduce((sum,p) => sum + p.price, 0)}</strong></p><p>{deliveryRisk(state.brief, Math.max(...suggested.map(p => p.etaDays)))}</p></> : <p>No outfit fits the listed size and merchandise budget. Adjust your brief to explore alternatives.</p>}</div></section>
      <section id="shopping-bag" className={styles.panel}><p className={styles.eyebrow}>YOUR SHOPPING TRIP</p><h2>A bag full of possibilities.</h2><p>Local mock cart. No inventory is held. This tab keeps your brief, bag and demo orders across page navigation.</p>{!state.cart.length ? <p className={styles.empty}>Your bag is empty. Choose a demo size and add a discovery above.</p> : <>{state.cart.map(line => { const p = catalog.find(item => item.id === line.productId)!; return <div className={styles.cartLine} key={`${p.id}-${line.size}`}><div><strong>{p.name}</strong><small>{p.retailer} · {line.size} · Quantity {line.quantity}</small></div><span>${p.price * line.quantity}</span><button onClick={() => remove(p.id,line.size)}>Remove</button></div>; })}<div className={styles.summary}><strong>Merchandise subtotal: ${total} USD</strong><p>Shipping / taxes / duties: not calculated. This is not a final payable total.</p>{state.brief.budget && total > Number(state.brief.budget) && <p className={styles.risk}>Over your merchandise budget by ${(total - Number(state.brief.budget)).toFixed(2)}.</p>}<p>{timing}</p><button disabled={!ready} className={styles.primary} onClick={checkout}>Create mock order · No payment</button></div></>}
        {state.orders.map(order => <article className={styles.order} key={order.id}><h3>{order.id} · Local demo order</h3><p>{order.lines.length} variants · ${order.total} merchandise · Destination: {order.brief.destination}</p><p>Event: {order.brief.eventDate || "Not provided"} · Occasion: {order.brief.occasion || "Not provided"}</p><p>No purchase was made, no retailer contacted and no shipment created. Flow integration is the next milestone.</p></article>)}
      </section>
      <ShoppingSessions product={schedule} request={context} onClose={() => setSchedule(null)} />
      {question && <ProductQuestions key={question.id} product={question} request={context} matchReason="You selected this product while exploring a fictional store. Suitability is not verified." onClose={() => setQuestion(null)} onSchedule={() => { setSchedule(question.name); setQuestion(null); }} />}
      <footer className={styles.footer}>IndiaAnytime <span>India. Always Open.</span></footer>
    </div>
  </main>;
}
